name: test
on:
  push:
    branches:
      - "**"
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:0.12.5
        ports:
          - 4566:4566
        env:
          SERVICES: dynamodb

    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: checkout
        uses: actions/checkout@v2

      - name: Install GolangCI-Lint
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.34.1

      - name: Run GolangCI-Lint
        run: ./bin/golangci-lint run --config .golangci.yml

      - name: Install AWS CLI
        run: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - name: Set up AWS profile
        run: |
            aws configure set aws_access_key_id dummy
            aws configure set aws_secret_access_key dummy
            aws configure set region ap-northeast-1
            aws configure set cli_pager ""

      - name: test
        run: go test -v ./...
